on:  
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Running Horus Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash
        horusec start -p ./ -G "true" -o="json" -O="./output.json"
    - uses: actions/upload-artifact@v2
      with:
        name: horusec-output
        path: ./output.json
